name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3️⃣ Verify the AWS identity
      - name: Verify AWS identity
        run: aws sts get-caller-identity

      # 4️⃣ Update kubeconfig for the EKS cluster
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name demo-cluster --region us-east-1
          kubectl get nodes

      # 5️⃣ Optional: Deploy your app
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
