name: Deploy to ArgoCD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Install ArgoCD CLI if not already installed
      - name: Install ArgoCD CLI
        run: |
          if ! command -v argocd &> /dev/null
          then
            curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
            chmod +x argocd
            sudo mv argocd /usr/local/bin/
          fi

      # 3️⃣ Login to ArgoCD using admin credentials
      - name: Login to ArgoCD
        run: |
          argocd login ${{ secrets.ARGOCD_SERVER }} \
            --username admin \
            --password ${{ secrets.ARGOCD_PASSWORD }} \
            --insecure

      # 4️⃣ Sync the ArgoCD application
      - name: Sync ArgoCD application
        run: |
          argocd app sync tetris-game
          argocd app wait tetris-game --health --timeout 300
